version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwertyui
    ports:
      - "3306"
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
